name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Checkout pyradiance
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and test
      run: |
        git submodule update --init --recursive
        pip install .
        cd test
        pytest


  build_test_osx:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Checkout pyradiance
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and test
      run: |
        git submodule update --init --recursive
        pip install .
        cd test
        pytest


  build_test_windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout pyradiance
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        git submodule update --init --recursive
        pip install .

    - name: Test
      run: |
        cd test
        pytest 
