# This workflow will upload a Python Package using Twine when a release is created

name: Upload Python Package

on:
  release:
    types: [published]

  # run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-all:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout pyradiance
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel

    - name: Build wheels
      run: python -m cibuildwheel --output-dir dist
      env:
        CIBW_BUILD: cp310-*
        # Skip PyPy
        CIBW_SKIP: "*-musllinux* pp*"

    - name: upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}
        path: ./dist/*.whl


  publish-pypi:
    runs-on: ubuntu-latest
    needs: build-all
    environment:
      name: pypi
      url: https://pypi.org/p/pyradiance
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    strategy:
      fail-fast: false

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: downloaded_dist

    - name: Create dist directory
      run: mkdir -p dist

    - name: Move wheels to dist directory
      run: |
        find downloaded_dist -name "*.whl" -exec mv {} dist/ \;

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
