name: Upload Python Package

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build-all:

    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout pyradiance
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
        CIBW_SKIP: "*-win32 *-manylinux_i686"
        CIBW_ARCHS_LINUX: "x86_64"
        CIBW_ARCHS_MACOS: "x86_64 arm64"
        CIBW_ARCHS_WINDOWS: "AMD64"
        # Set a newer macOS deployment target to support modern C++ features
        # required by dependencies like nanobind.
        CIBW_MACOSX_DEPLOYMENT_TARGET: "10.15"
        CIBW_TEST_COMMAND: "python {project}/ci_test.py"
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
        CIBW_TEST_SKIP: "*-win*"

    - name: upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}-python-${{ matrix.python-version }}
        path: ./wheelhouse/*.whl
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false


  publish-pypi:
    runs-on: ubuntu-latest
    needs: build-all
    environment:
      name: pypi
      url: https://pypi.org/p/pyradiance
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    strategy:
      fail-fast: false

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: dist-*
        path: dist/
        merge-multiple: true

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
