# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
      
  # run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pypi-publish_linux:
    name: Upload Linux release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyradiance
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Checkout pyradiance
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build Wheels
      run: |
        git submodule update --init --recursive
        pip install requests wheel auditwheel pytest
        python setup.py bdist_wheel

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  pypi-publish_macos:
    name: Upload macOS release to PyPI
    runs-on: macos-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyradiance
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Checkout pyradiance
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build Wheels
      run: |
        git submodule update --init --recursive
        pip install requests wheel auditwheel pytest
        python setup.py bdist_wheel

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1


  pypi-publish_windows:
    name: Upload Windows release to PyPI
    runs-on: windows-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyradiance
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Checkout pyradiance
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build Wheels
      run: |
        git submodule update --init --recursive
        pip install requests wheel auditwheel pytest
        python setup.py bdist_wheel

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
